#!/usr/bin/env node
// Transform the raw wger CC-BY-SA exercise export into committed seed SQL.
//
// Reads the OFFLINE raw export saved by fetch-wger.mjs at
// supabase/seed/wger/exercises.json and emits idempotent INSERTs into
// public.exercises at supabase/seed.sql (the single path config.toml's
// [db.seed] sql_paths already loads on `supabase db reset`).
//
// Fails loudly (non-zero exit, clear message) if the export is missing or its
// shape is not what the transform expects — there is no silent partial seed.
//
// Data source: wger Workout Manager (https://wger.de), exercise database
// licensed CC-BY-SA 4.0. See supabase/ATTRIBUTION.md.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SELF_DIR = dirname(fileURLToPath(import.meta.url));
const SUPABASE_DIR = join(SELF_DIR, "..");
const RAW_FILE = join(SELF_DIR, "wger", "exercises.json");
const OUT_FILE = join(SUPABASE_DIR, "seed.sql");
const LANGUAGE_EN = 2;
const DEFAULT_LICENSE = "CC-BY-SA 4.0";
const DEFAULT_AUTHOR = "wger.de";

function fail(message) {
  console.error(`import-wger failed: ${message}`);
  process.exit(1);
}

function readExport() {
  let raw;
  try {
    raw = readFileSync(RAW_FILE, "utf8");
  } catch {
    fail(
      `raw export not found at ${RAW_FILE}. ` +
        `Run 'node supabase/seed/fetch-wger.mjs' first. ` +
        `Expected a JSON array of wger exerciseinfo objects ` +
        `(each with translations[], category, muscles[], equipment[], license, license_author).`,
    );
  }
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    fail(`raw export at ${RAW_FILE} is not valid JSON: ${err.message}`);
  }
  if (!Array.isArray(parsed) || parsed.length === 0) {
    fail(`raw export at ${RAW_FILE} must be a non-empty JSON array, got ${typeof parsed}`);
  }
  return parsed;
}

function assertArray(value, label, id) {
  if (value !== undefined && value !== null && !Array.isArray(value)) {
    fail(`exercise ${id}: expected '${label}' to be an array, got ${typeof value}`);
  }
}

// Friendly English muscle/equipment name, trimmed; "" when unusable.
function muscleName(m) {
  const n = (m && (m.name_en || m.name)) || "";
  return n.trim();
}

function names(list, pick) {
  const out = [];
  const seen = new Set();
  for (const item of list || []) {
    const n = pick(item);
    if (n && !seen.has(n)) {
      seen.add(n);
      out.push(n);
    }
  }
  return out;
}

function englishName(exercise) {
  assertArray(exercise.translations, "translations", exercise.id);
  const en = (exercise.translations || []).find(
    (t) => t && t.language === LANGUAGE_EN && typeof t.name === "string" && t.name.trim(),
  );
  return en ? en.name.trim() : null;
}

function toRow(exercise) {
  const name = englishName(exercise);
  if (!name) {
    fail(
      `exercise ${exercise.id} (uuid ${exercise.uuid}) has no English (language=${LANGUAGE_EN}) ` +
        `translation name; export shape unexpected, refusing a partial seed.`,
    );
  }
  if (exercise.category !== null && exercise.category !== undefined && typeof exercise.category !== "object") {
    fail(`exercise ${exercise.id}: expected 'category' to be an object or null`);
  }
  assertArray(exercise.muscles, "muscles", exercise.id);
  assertArray(exercise.equipment, "equipment", exercise.id);

  const category = exercise.category && exercise.category.name ? exercise.category.name.trim() : null;
  const muscles = names(exercise.muscles, muscleName);
  const equipment = names(exercise.equipment, (e) => (e && e.name ? e.name.trim() : ""));
  const license = (exercise.license && exercise.license.short_name && exercise.license.short_name.trim()) || DEFAULT_LICENSE;
  const licenseAuthor = (typeof exercise.license_author === "string" && exercise.license_author.trim()) || DEFAULT_AUTHOR;

  return { name, category, muscles, equipment, license, licenseAuthor };
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlNullableString(value) {
  return value === null || value === undefined ? "null" : sqlString(value);
}

function sqlTextArray(values) {
  if (values.length === 0) return "array[]::text[]";
  return `array[${values.map(sqlString).join(", ")}]::text[]`;
}

function buildSql(rows) {
  const header = [
    "-- public.exercises catalog seed — GENERATED by supabase/seed/import-wger.mjs.",
    "-- Do not edit by hand; re-run 'node supabase/seed/import-wger.mjs' to regenerate.",
    "--",
    "-- Data source: wger Workout Manager (https://wger.de) exercise database,",
    "-- licensed CC-BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/).",
    "-- This seed is a derivative; share-alike applies. See supabase/ATTRIBUTION.md.",
    "--",
    `-- ${rows.length} exercises, English (language=${LANGUAGE_EN}) catalog.`,
    "",
    "-- Idempotent: inserts only names not already present, so re-running the seed",
    "-- (or loading it on a populated DB) adds no duplicates and touches no FK rows.",
    "insert into public.exercises (name, category, muscles, equipment, license, license_author)",
    "select v.name, v.category, v.muscles, v.equipment, v.license, v.license_author",
    "from (values",
  ];

  const valueLines = rows.map((r, i) => {
    const tuple =
      `  (${sqlString(r.name)}, ${sqlNullableString(r.category)}, ${sqlTextArray(r.muscles)}, ` +
      `${sqlTextArray(r.equipment)}, ${sqlString(r.license)}, ${sqlString(r.licenseAuthor)})`;
    return tuple + (i === rows.length - 1 ? "" : ",");
  });

  const footer = [
    ") as v(name, category, muscles, equipment, license, license_author)",
    "where not exists (select 1 from public.exercises e where e.name = v.name);",
    "",
  ];

  return [...header, ...valueLines, ...footer].join("\n");
}

function main() {
  const exercises = readExport();
  const byName = new Map();
  let dupes = 0;
  for (const exercise of exercises) {
    if (!exercise || typeof exercise !== "object") {
      fail("export contains a non-object entry; shape unexpected");
    }
    const row = toRow(exercise);
    const key = row.name.toLowerCase();
    if (byName.has(key)) {
      dupes += 1;
      continue;
    }
    byName.set(key, row);
  }
  const rows = [...byName.values()];
  if (rows.length === 0) {
    fail("no exercises produced from the export; refusing to write an empty seed");
  }
  writeFileSync(OUT_FILE, buildSql(rows));
  console.log(
    `Wrote ${rows.length} exercises to ${OUT_FILE} ` +
      `(${exercises.length} source items, ${dupes} duplicate names collapsed).`,
  );
}

main();
