/**
 * Integration check for the idempotent enrichment routine (issue #48) against
 * the local Supabase stack. It exercises the routine's REAL SQL apply path
 * (generated by buildEnrichSql, applied as the DB owner exactly like
 * enrich-exercises.mjs) on fixture catalog rows and asserts:
 *  - the update is additive and matched by lower(name),
 *  - re-running produces NO diff (true idempotency),
 *  - free-exercise-db text fills only an empty wger instruction list,
 *  - no fixture ends up with a free-exercise-db-shaped image_path,
 *  - the importer guard rejects SQL carrying a free-exercise-db image path.
 * Fixtures use a random suffix so parallel/repeat runs never collide, and are
 * removed in teardown. Requires `supabase start` (docker container
 * supabase_db_rack), the same local stack the other integration tests use.
 * See docs/specs/spec-exercise-detail.md.
 */

import { spawnSync } from 'node:child_process';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { buildEnrichSql, type EnrichmentPatch } from '../../supabase/seed/enrich/transform.mjs';

const PSQL = (
  process.env.RACK_PSQL ?? 'docker exec -i supabase_db_rack psql -U postgres -d postgres'
)
  .split(' ')
  .filter(Boolean);

function runSql(sql: string): string {
  const [cmd, ...args] = PSQL;
  const res = spawnSync(cmd!, [...args, '-v', 'ON_ERROR_STOP=1', '-At', '-q'], {
    input: sql,
    encoding: 'utf8',
  });
  if (res.status !== 0) {
    throw new Error(`psql exited ${res.status}: ${res.stderr || res.stdout}`);
  }
  return res.stdout.trim();
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const suffix = Math.random().toString(16).slice(2, 10);
const wgerName = `ITest Wger ${suffix}`;
const fedName = `ITest Fed ${suffix}`;

beforeAll(() => {
  // Insert fixture catalog rows as the DB owner (the seed/enrichment privilege),
  // both starting with empty detail fields, like a freshly seeded Phase 1 row.
  runSql(
    `insert into public.exercises (name, category, muscles, equipment) values
      (${sqlString(wgerName)}, 'Chest', array['Chest']::text[], array['Barbell']::text[]),
      (${sqlString(fedName)}, 'Abs', array['Abs']::text[], array[]::text[]);`,
  );
});

afterAll(() => {
  // Another parallel test's seedPlanTree may have picked a fixture row via an
  // unordered limit(1) and created a plan_exercises FK to it. Remove only the
  // rows that reference THESE fixtures (and their set_logs) before deleting the
  // fixtures, so teardown never touches unrelated catalog or user data.
  const fixtureIds = `(select id from public.exercises where name in (${sqlString(
    wgerName,
  )}, ${sqlString(fedName)}))`;
  runSql(
    `delete from public.set_logs where plan_exercise_id in
       (select id from public.plan_exercises where exercise_id in ${fixtureIds});
     delete from public.plan_exercises where exercise_id in ${fixtureIds};
     delete from public.exercises where name in (${sqlString(wgerName)}, ${sqlString(fedName)});`,
  );
});

function patches(): EnrichmentPatch[] {
  return [
    {
      key: wgerName.toLowerCase(),
      name: wgerName,
      instructions: ['Lie on the bench', 'Press the bar up'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps'],
      imageKey: `192/${suffix}.png`,
      imageUrl: `https://wger.de/media/exercise-images/192/${suffix}.png`,
      instructionsSource: 'wger',
    },
    {
      key: fedName.toLowerCase(),
      name: fedName,
      instructions: ['Lie on the floor', 'Curl your torso up'],
      primaryMuscles: ['abdominals'],
      secondaryMuscles: [],
      imageKey: null,
      imageUrl: null,
      instructionsSource: 'free-exercise-db',
    },
  ];
}

function snapshot(): string {
  return runSql(
    `select coalesce(array_to_string(instructions, '~'), '') || '|' ||
            coalesce(array_to_string(primary_muscles, '~'), '') || '|' ||
            coalesce(array_to_string(secondary_muscles, '~'), '') || '|' ||
            coalesce(image_path, '')
     from public.exercises
     where name in (${sqlString(wgerName)}, ${sqlString(fedName)})
     order by name;`,
  );
}

describe('enrichment routine idempotency + guard (local DB)', () => {
  it('applies enrichment additively and is idempotent (no diff on re-run)', () => {
    const sql = buildEnrichSql(patches());
    runSql(sql);
    const first = snapshot();
    runSql(sql);
    const second = snapshot();
    expect(second).toBe(first);
    expect(first).toContain('Press the bar up');
    expect(first).toContain('Curl your torso up');
    expect(first).toContain(`192/${suffix}.png`);
  });

  it('leaves no free-exercise-db-shaped image_path in the catalog', () => {
    const fedShaped = runSql(
      `select count(*) from public.exercises
       where image_path ~ '/[0-9]+\\.(jpg|jpeg|png|gif|webp)$'
         and image_path !~ '^[0-9]+/';`,
    );
    expect(Number(fedShaped)).toBe(0);
  });

  it('does not overwrite existing instructions on re-run (additive coalesce)', () => {
    runSql(buildEnrichSql(patches()));
    // Tamper one row with manual instructions, then re-apply: coalesce must keep
    // the existing non-empty value rather than reset it.
    runSql(
      `update public.exercises set instructions = array['manual edit']::text[]
       where name = ${sqlString(wgerName)};`,
    );
    runSql(buildEnrichSql(patches()));
    const kept = runSql(
      `select array_to_string(instructions, '~') from public.exercises
       where name = ${sqlString(wgerName)};`,
    );
    expect(kept).toBe('manual edit');
  });

  it('refuses to emit SQL carrying a free-exercise-db image path', () => {
    const tampered = patches();
    tampered[0]!.imageKey = 'Bench_Press/0.jpg';
    expect(() => buildEnrichSql(tampered)).toThrow(/free-exercise-db image path/);
  });
});
